spring.application.name=recipe-hub

spring.datasource.url=jdbc:postgresql://localhost:5432/recipe_hub
spring.datasource.username=recipe_hub
spring.datasource.password=recipe_hub
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
